services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: chrome_selenium
    depends_on:
      - app
    ports:
      - 4444:4444
    environment:
      - VNC_NO_PASSWORD=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
      - SE_SCREEN_WIDTH=2560
      - SE_SCREEN_HEIGHT=1440
    restart: always
    shm_size: 2gb
    networks:
      - selenium

  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/app
    container_name: test-selenium
    restart: unless-stopped
    tty: true
    environment: []
    command: >
      python3 /var/www/app/main_driver_code_headless.py
    volumes:
      - C:/Users/Sanchit/Desktop/scholarship-POM_E2E:/var/www/app
    shm_size: 2gb
    networks:
      - selenium

networks:
  selenium:
    driver: bridge